#!/bin/bash

# CURRENT_TEMPERATURE=$REDSHIFT_TEMPERATURE # 4500
CURRENT_TEMPERATURE=4500
INTERVAL=2500
NEW_TEMPERATURE=$(($CURRENT_TEMPERATURE-$INTERVAL))
redshift -P -O $NEW_TEMPERATURE
CURRENT_TEMPERATURE=$NEW_TEMPERATURE
