#!/bin/bash

export DEFAULT_COMFYUI_PORT=7861
export DELAY_BEFORE_BROWSER_LAUNCH=3 # seconds
export BROWSER=/usr/bin/firefox

cd "$HOME"/area/ai/tools/Fooocus || exit
source fooocus_env/bin/activate
firejail --net=none python3 webui.py &
# sleep "$DELAY_BEFORE_BROWSER_LAUNCH"
# "$BROWSER" http://127.0.0.1:"$DEFAULT_COMFYUI_PORT"
