#!/bin/bash

export DEFAULT_COMFYUI_PORT=8188
export DELAY_BEFORE_BROWSER_LAUNCH=3 # seconds
export PATH_TO_BROWSER=/usr/bin/firefox

cd "$HOME"/area/ai/tools/ComfyUI-Installer/ComfyUI || exit
firejail --net=none ./ComfyUI &
sleep "$DELAY_BEFORE_BROWSER_LAUNCH"
"$PATH_TO_BROWSER" http://127.0.0.1:"$DEFAULT_COMFYUI_PORT"
