#!/usr/bin/env bash

setxkbmap tr &                              # set keyboard layout
setxkbmap -option caps:swapescape &         # swap esc with caps lock
xrandr -s 1920x1080 &                       # set resolution
unclutter -idle 2 &                         # disable mouse cursor
xset r rate 150 90 &                        # increase speed of keyboard
xset s off &                                # disable screen saver
xset -dpms &                                # disable monitor shutdown
xset -b &                                   # dissable annoying desktop bell sound
picom -b &                                  # start compositor for opacity/fading stuff
mpd &                                       # start music server
dunst &                                     # start notification daemon
sxhkd -m 1 &                                # keyboard shortcuts
# lxsession &                                 # auth agent and other good stuff
wpctl set-volume @DEFAULT_AUDIO_SINK@ 30% & # set pipewire volume to 30%
adaptive-blue-light-filter &                # blue light filter
slstatus &                                  # status bar
udiskie &                                   # auto mount usb
periodic-random-wallpaper-switcher &        # random wallpaper

# auto start programs
emacs &
librewolf &
logseq &
ferdium &
