#!/usr/bin/env bash

function run_dmenu() {
    dmenu -l 10 \
        -b \
        -fn "IosevkaTerm NF:size=14:style=Regular" \
        -nb "#222222" \
        -nf "#bbbbbb" \
        -sb "#005577" \
        -sf "#eeeeee"
}

PROCESS="$(ps aux | grep "^savolla" | awk '{print $11}' | sed 's/\/.*\///' | uniq | run_dmenu)"

# Ask for confirmation before killing the process
CONFIRMATION=$(echo -e "no\nyes" | dmenu \
    -b \
    -n \
    -fn "IosevkaTerm NF:size=14:style=Regular" \
    -nb "#222222" \
    -nf "#bbbbbb" \
    -sb "#005577" \
    -sf "#eeeeee" \
    -p "Are you sure you want to stop $PROCESS?")

if [[ "$CONFIRMATION" == "yes" ]]; then
    for pid in $(pgrep "$PROCESS")
    do
        kill -SIGSTOP $pid
    done
    notify-send "Process $PROCESS suspended."
else
    notify-send "Action cancelled."
fi
