#!/usr/bin/env bash

# Define the path to the lock file
LOCK_FILE="/tmp/start-screen-recording-xorg.lock"
FPS=45

# Check if the lock file already exists
if [ -e "$LOCK_FILE" ]; then
  echo "Script is already running."
  notify-send -r 27072 "screen recorder" "ERROR: script is already running"
  exit 1
fi

# Create the lock file
touch "$LOCK_FILE"

# Add a trap to delete the lock file on exit (even if the script fails)
trap "rm -f $LOCK_FILE" EXIT

appimage-run "$APPIMAGE_DIR"/Mechvibes-2.3.6-hotfix.AppImage --no-sandbox &
pkill -f dunst # prevent private things on screen casts
pkill -f periodic-random-wallpaper-switcher
mv ~/.zsh-history ~/.zsh-history.back # disable history commands during screencast

ffmpeg -f x11grab \
  -s $(xrandr | grep '*' | awk '{print $1}' | head -n 1) \
  -framerate "$FPS" \
  -i :0.0 \
  -f pulse \
  -i $(pactl get-default-sink).monitor \
  $HOME/resource/videos/screencasts/"screencast-$(date +'%Y-%m-%d_%H-%M-%S').mp4" &

screenkey &

echo "RECORDING_SCREEN_BY_USER=1" >/tmp/is-screen-recording
