#!/usr/bin/env bash

# Define the path to the lock file
# LOCK_FILE="/tmp/tmux-session-creator.lock"

# Check if the lock file already exists
# if [ -e "$LOCK_FILE" ]; then
#   echo "Script is already running."
#   exit 1
# fi

# Create the lock file
# touch "$LOCK_FILE"

# Add a trap to delete the lock file on exit (even if the script fails)
# trap 'rm -f $LOCK_FILE' EXIT

tmux new-session -d -s main "zsh"

# tmux rename-window -t main:1 " :emacs"
# tmux send-keys -t main:1 "$HOME/.config/emacs/bin/doom sync" C-m # I use my home accross different machines and emacs needs this all the time
# tmux send-keys -t main:1 "$HOME/.config/emacs/bin/doom run -nw" C-m
# tmux rename-window -t main:1 " :neovim"
# tmux send-keys -t main:1 "nvim" C-m

# tmux new-window -t main:2 "zsh"           # create a scratch window
# tmux rename-window -t main:2 " :scratch" # rename window 1

tmux new-window -t main:1 "zsh"           # create a scratch window
tmux rename-window -t main:1 " :scratch" # rename window 1

# launch tui progrrams on another session
tmux new-session -d -s programs "weechat"
tmux rename-window -t programs:1 "󰭹 :irc"

tmux new-window -t programs:2 "zsh"
tmux send-keys -t programs:2 "ncmpcpp" C-m
tmux split-window -t programs:2 "ncmpcpp -c ~/.config/ncmpcpp/visualizer.config -s visualizer"
tmux select-pane -t programs:2.1 # Focus the first ncmpcpp pane
tmux rename-window -t programs:2 " :music"

tmux new-window -t programs:3 "zsh"
tmux send-keys -t programs:3 "newsboat" C-m
tmux rename-window -t programs:3 " :rss"

tmux new-window -t programs:4 "weather 2 Gölcük"
tmux rename-window -t programs:4 " :weather" # rename the weather window
tmux split-window -h -t programs:4 "weather 1 İzmit | head -n 6"
tmux split-window -t programs:4 "weather 1 Kherson | head -n 6"
tmux split-window -t programs:4 "weather 1 Erzurum | head -n 6"

tmux new-window -t programs:5 "zsh"
tmux send-keys -t programs:5 "btop" C-m
tmux rename-window -t programs:5 " :monitor" # rename the weather window

tmux new-window -t programs:6 "zsh"
tmux send-keys -t programs:6 "journalctl -f" C-m
tmux rename-window -t programs:6 " :logs" # rename the logs window

# select session and window at the end
tmux attach-session -t main:1
